# Generated by Django 5.0.6 on 2024-07-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', null=True, upload_to='perfiles/'),
        ),
    ]
